SET LINESIZE 170
SET pagesize 30
col username format a15
col OBJECT_NAME  format a20
col limit format a20
col segment_name format a20
col owner format a13
col id format a13
col user format a15
col  PARTITION_NAME format a20
col file_name format a30
col  granted_role format a20
col role format a25
col name format a23
col DEFAULT_TABLESPACE format a15
col TEMPORARY_TABLESPACE format a15
col created format a13
col DEFAULT_COLLATION format a20
col table_name format a15
col grantee format a15
col grantor format a15
col privilege format a25
col ADMIN_OPTION format a10
col COMMON format a8
col INHERITED format a10
col user_id format a15
col password format a15
col profile format a15
col tablespace_name format a15
col CLUSTER_NAME format a15
col LOCALTIMESTAMP format a30
col CURRENT_TIMESTAMP format a35
