/*
--------------------------------------------------------------------
© 2017 sqlservertutorial.net All Rights Reserved
--------------------------------------------------------------------
Name   : BikeStores
Link   : http://www.sqlservertutorial.net/load-sample-database/
Version: 1.0
--------------------------------------------------------------------
*/
-- create schemas
-- create tables
CREATE TABLE abdel.categories (
	category_id INT PRIMARY KEY,
	category_name VARCHAR (255) NOT NULL
);

CREATE TABLE abdel.brands (
	brand_id INT PRIMARY KEY,
	brand_name VARCHAR (255) NOT NULL
);

CREATE TABLE abdel.products (
	product_id INT GENERATED by default on null as IDENTITY PRIMARY KEY,
	product_name VARCHAR (255) NOT NULL,
	brand_id INT NOT NULL,
	category_id INT NOT NULL,
	model_year SMALLINT NOT NULL,
	list_price DECIMAL (10, 2) NOT NULL,
	FOREIGN KEY (category_id) REFERENCES abdel.categories (category_id) ON DELETE CASCADE,
	FOREIGN KEY (brand_id) REFERENCES abdel.brands (brand_id) ON DELETE CASCADE
);

CREATE TABLE abdel.customers (
	customer_id INT GENERATED by default on null as IDENTITY PRIMARY KEY,
	first_name VARCHAR (255) NOT NULL,
	last_name VARCHAR (255) NOT NULL,
	phone VARCHAR (25),
	email VARCHAR (255) NOT NULL,
	street VARCHAR (255),
	city VARCHAR (50),
	state VARCHAR (25),
	zip_code VARCHAR (5)
);

CREATE TABLE abdel.stores (
	store_id INT GENERATED by default on null as IDENTITY PRIMARY KEY,
	store_name VARCHAR (255) NOT NULL,
	phone VARCHAR (25),
	email VARCHAR (255),
	street VARCHAR (255),
	city VARCHAR (255),
	state VARCHAR (10),
	zip_code VARCHAR (5)
);

CREATE TABLE abdel.staffs (
	staff_id INT GENERATED by default on null as IDENTITY PRIMARY KEY,
	first_name VARCHAR (50) NOT NULL,
	last_name VARCHAR (50) NOT NULL,
	email VARCHAR (255) NOT NULL UNIQUE,
	phone VARCHAR (25),
	active INT NOT NULL,
	store_id INT NOT NULL,
	manager_id INT,
	FOREIGN KEY (store_id) REFERENCES abdel.stores (store_id) ON DELETE CASCADE,
	FOREIGN KEY (manager_id) REFERENCES abdel.staffs (staff_id) ON DELETE SET NULL
);

CREATE TABLE abdel.orders (
	order_id INT GENERATED by default on null as IDENTITY PRIMARY KEY,
	customer_id INT,
	order_status INT NOT NULL,
	order_date DATE NOT NULL,
	required_date DATE NOT NULL,
	shipped_date DATE,
	store_id INT NOT NULL,
	staff_id INT NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES abdel.customers (customer_id) ON DELETE CASCADE,
	FOREIGN KEY (store_id) REFERENCES abdel.stores (store_id) ON DELETE CASCADE,
	FOREIGN KEY (staff_id) REFERENCES abdel.staffs (staff_id) ON DELETE SET NULL
);

CREATE TABLE abdel.order_items (
	order_id INT GENERATED by default on null as IDENTITY,
	item_id INT,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	list_price DECIMAL (10, 2) NOT NULL,
	discount DECIMAL (4, 2) DEFAULT 0 NOT NULL,
	PRIMARY KEY (order_id, item_id),
	FOREIGN KEY (order_id) REFERENCES abdel.orders (order_id) ON DELETE CASCADE,
	FOREIGN KEY (product_id) REFERENCES abdel.products (product_id) ON DELETE CASCADE
);

CREATE TABLE abdel.stocks (
	store_id INT GENERATED by default on null as IDENTITY,
	product_id INT,
	quantity INT,
	PRIMARY KEY (store_id, product_id),
	FOREIGN KEY (store_id) REFERENCES abdel.stores (store_id) ON DELETE CASCADE,
	FOREIGN KEY (product_id) REFERENCES abdel.products (product_id) ON DELETE CASCADE
);

